dependencies:
  flutter:
    sdk: flutter
  flutter_iframe_webview: ^1.0.0
  flutter_jsbridge_sdk: ^1.0.2
  universal_platform: ^1.1.0
  webview_cef:
    git: https://github.com/OpenBonfire/webview_cef
  webview_flutter_platform_interface: ^2.10.0
  webview_windows: ^0.4.0
dependency_overrides:
  webview_flutter:
    git:
      path: packages/webview_flutter/webview_flutter
      url: https://gitee.com/openharmony-sig/flutter_packages.git
description: Cross-platform, inline Webviews for Flutter.
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
environment:
  flutter: '>=1.17.0'
  sdk: ^3.4.0
flutter: null
homepage: null
name: fireview
publish_to: none
version: 0.0.1
